### ISSUE TITLE
Ability to test scopes

### ISSUE THREAD

**Issue by DannyBen** [ProctorU/policy-assertions#13]
Hi - I understand [this gem is probably not maintained][1] - but is there currently a recommended pattern for testing that the scope returned by the policy matches the expectations?

Should I just do something like this? Is there a shorter / cleaner way?

```ruby
expected = 10
actual = described_class::Scope.new(user, record).resolve.count
assert_equal expected, actual
```

[1]: https://github.com/ProctorU/policy-assertions/issues/7#issuecomment-296698931

**Comment by chevinbrown** [comment]
@DannyBen, we're open to suggestions here. Your proposed method looks fine. Scoping is really just an active record interface, so the actual tests aren't as cut-and-dry as policy tests are.

In my experience, testing that a user _can_ get some records that you expect, or that another user _can't_ get records that you expect they should not has sufficed. 

Are you encountering an issue, or do you expect that the gem should do something more?

**Comment by DannyBen** [comment]
It would have been nice if the gem could provide a method for accessing the scope class.

I added this method I expected to find in the gem to my `test_helper`:

```ruby
module PolicyHelper
  def scope(user, record)
    described_class::Scope.new(user, record).resolve
  end
end
```
and in my tests I can now dp

```ruby
assert_equal 20, scope(admin, User).count
assert_equal 1, scope(regular_user, User).count
```

**Comment by chevinbrown** [comment]
@licatajustin @king601 what do you think? 
We could probably add that.

@DannyBen would you be interested in helping with a PR?

**Comment by chevinbrown** [comment]
@DannyBen, how has that worked for you? I'm open to adding a simple helper to the library!

**Comment by DannyBen** [comment]
Oh, sorry for not replying sooner - I was busy when GitHub first notified, and then it slipped my mind...

Yes - the helper that I mentioned above works nicely and helps to keep the specs clean and neat. Not sure I will have time to deal with creating a PR, mainly because it will probably take me some time to orientate myself in the codebase, but I do think such a helper is a good idea.

**Comment by licatajustin** [comment]
Good with us. Will gladly review a PR 🥇
