### ISSUE TITLE
Unclear msg output for users

### ISSUE THREAD

**Issue by BKSpurgeon** [ProctorU/policy-assertions#16]
Hi there

thank you for this gem.

Here is a sample out put:
```shell
Expected ProjectPolicy to grant update? on #<Project:0x00007f7d04514ef0> for #<User:0x00007f7d045001a8> but it didn't
```
The msg prints the user object. Is it possible to monkey patch it so that the msg is more meaningful?

Looks like it is coming from this line: https://github.com/ProctorU/policy-assertions/blob/c6fc7cdc4c1e647344282e605c643d04984c5764/lib/policy_assertions.rb#L18

Or should I simply monkey patch `user.to_s`? but woulld you know how to do that only within the context of the `PolicyAssertions::Test` class? Pointers would be appreciated.

regards

Ben

**Comment by chevinbrown** [comment]
@BKSpurgeon thanks for the report, I agree...
A PR for improving this would be welcomed. 😃

**Comment by BKSpurgeon** [comment]
Shall I assume that users will have an email, and if that exists, then to monkey patch the users class?

Something like this:

```ruby
module PolicyAssertions
  class Test < ActiveSupport::TestCase
    def monkey_patch_user(user)
      if user.class.method_defined?(:email)
        user.class_eval do
          def to_s
            user.email
          end
        end
      end
    end

    def assert_permit(user, record, *permissions)
      monkey_patch_user(user)
      get_permissions(permissions.flatten).each do |permission|
        policy = find_policy!(user, record)
        assert policy.public_send(permission),
          "Expected #{policy.class.name} to grant #{permission} "\
          "on #{record} for #{user.email} but it didn't"
      end
    end
  end
end
```

Or should I merely add some instructions in the read me so as to enable users to set it up themselves?

**Comment by chevinbrown** [comment]
We should probably improve the entire experience by doing something more like this (untested):

```
    def assert_permit(user, record, *permissions)
      get_permissions(permissions.flatten).each do |permission|
        policy = find_policy!(user, record)
        assert policy.public_send(permission),
          "Expected #{policy.class.name} to grant #{permission} "\
          "on #{record.to_s} for #{user.to_s} but it didn't"
      end
    end
  end
end
```
That would allow you to define `#to_s` within your application code, _or_ potentially leverage [refinements](https://medium.com/rubycademy/refine-and-using-methods-in-ruby-part-i-2aef6d7a4325). 
I wouldn't go so far as to put a method inline in the actual gem source; you should probably find a way to do the above suggestion and then monkey-patch `to_s` for you test-case classes.

I would suggest trying the above modification first and maybe we can settle on a good way to improve the gem from there.

**Comment by BKSpurgeon** [comment]
In that case, how about I just edit the document to show how to add test specific monkey patching?

**Comment by BKSpurgeon** [comment]
https://github.com/ProctorU/policy-assertions/pull/17

Hopefully that helps?

**Comment by chevinbrown** [comment]
LGTM. 👍 thanks for this!

**Comment by aximuseng** [comment]
Related issue here if anyone can comment. https://github.com/ProctorU/policy-assertions/issues/19
