### ISSUE TITLE
Test Output Results Question

### ISSUE THREAD

**Issue by aximuseng** [ProctorU/policy-assertions#19]
I am following the docs on this but in my case I have an added scope to my policies - an enrollment which associates uses with a given tenant in my multi-tenant app.  So for example my tests look like this:

```
test 'guests can not comment' do
  refute_permit users(:guest).enrollment, AssetCategory, 'comment?'
end
```

When a test fails I get something like this:

`Expected AssetCategoryPolicy not to grant new? on AssetCategory for #<Enrollment:0x00007fb0890d8e00> but it did`

I tried to monkey patch like this:

```
module PatchEnrollment
  refine Enrollment do
    def to_s
      user.name_last
    end
  end
end

```

In my fixtures I created a user for each type of role they are assigned and made the last name the same for situations like this.  My hope was to have an output like this:

`Expected AssetCategoryPolicy not to grant new? on AssetCategory for Guest but it did`

My patch does not seem to be applied and throws no error (I do have `using PatchEnrollment` applied in my test_helper BTW).

Any ideas here?  Can anyone confirm that the documented monkey patch works?

**Comment by benkoshy** [comment]
@aximuseng 

## First try this:

```ruby
module PatchEnrollment
  refine Enrollment do
    def to_s
      "hello world"
    end
  end
end
```

## What I think is the problem:

```ruby
test 'guests can not comment' do
  refute_permit users(:guest).enrollment, AssetCategory, 'comment?'
end
```

Refute permit has the following method signature:

```ruby
def refute_permit(user, record, *permissions); end;
```

So the first argument requires a user, rather than an `Enrolement` object (unless you want your Enrolement object to act like a user?)

## Try this next:

In this case, I think you want to check for permissions against your Guest. So try this:

```ruby
# your test
refute_permit users(:guest), AssetCategory, 'comment?'
```

And the monkey patch must be applied to the user (or Guest model?) which ever it is:

```ruby
module PatchEnrollment
  refine User do  # not Enrolement
    def to_s
      user.name_last
    end
  end
end
```

rgds

Ben

**Comment by benkoshy** [comment]
@aximuseng i just realised - if you're ok to define `to_s` for your `User` or `Guest` model, then you needn't do this type of complex monkey patching. Monkey patching is only important if you want your testing environment  `@user.to_s` to be different from your production `@user.to_s`

**Comment by aximuseng** [comment]
Thanks @benkoshy I will try that. I suspect that's the easiest path. My Enrollment model is really just a fancy join table between the Company and User models. Not used for much else other than polices. I can't see how overriding that method will be an issue. 👍

**Comment by aximuseng** [comment]
Boom!  Doing the override the model was the way to go.  I have my tests cycle through all the enrolments in groups that I expect to grant / no grant vs. listing them one by one.  This way I know which one is not set correctly.

`Expected AssetPolicy to grant state? on Asset for Lead Operator but it didn't`
