### ISSUE TITLE
Can't work with assert_strong_parameters

### ISSUE THREAD

**Issue by jschaeff** [ProctorU/policy-assertions#5]
Hi,

thanks for this usefull gem. I'm trying to test the permitted attributes defined in my policy, but I don't get your example : 

`assert_strong_parameters(users(:staff), Article, article_attributes, params)`

What is "article_attributes" ? It should return a hash, I guess, but in my project, I don't have any "model_attributes" helper ... where does it come from ?

thanks.

**Comment by ksimmons** [comment]
Hi @jschaeff , sorry for the late reply. Check out the policy tests in this project. I think that will answer your question. If not let me know.

https://github.com/ksimmons/codedorm

**Comment by rubyconvict** [comment]
There's something terribly wrong with this test. Whatever I put in, in any argument, the test passes.

**Comment by chevinbrown** [comment]
@jschaeff, we have just transferred maintainers to @ProctorU/engineering. If this is still an issue, please resubmit a new ticket with more details.
