### ISSUE TITLE
Make it includable

### ISSUE THREAD

**Issue by pupeno** [ProctorU/policy-assertions#6]
It would be good if this gem provided a module that you can just include in your test class instead of a class you have to inherit from. For example:

https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#testunit

or (my own gem):

https://github.com/pupeno/assert_difference

You can still provide the class for people that want to use it and backward compatibility. If this is a change you'd be happy to adopt, I can provide the PR.

**Comment by chevinbrown** [comment]
I am for this change.

**Comment by chevinbrown** [comment]
@pupeno, open to accept a PR, but given the timeframe I'm closing this issue.

**Comment by chevinbrown** [comment]
@pupeno, closing due to timeframe, but I am open to a PR!
