### ISSUE TITLE
Override methods

### ISSUE THREAD

**Issue by jasper502** [ProctorU/policy-assertions#7]
It's not really an issue - more of a question:

I want to override assert_permit and refute_permit to make a slight tweak to the error message:
 
```
"Expected #{policy.class.name} to grant #{permission} "\
"on #{record} for #{user} but it didn't"

```
due to a slight difference in my Pundit set-up the `user` I authorize is a role with an associated user so I get:

```
Expected AreaPolicy to grant new? on Area for #<Enrollment:0x007fe58dc01de8> but it didn't
test/policies/area_policy_test.rb:20:in `test_new_and_create'
```

I just want to change #{user} to #{user.user}.  I know I could fork this etc. but it seems way easier to just override the methods.  Can I do this?

**Comment by ksimmons** [comment]
Hi @jasper502, sorry for such a late reply. I don't write much Ruby code these days. I can't think of any easy fix to this. I don't think overriding the method is the way to go. If you want to add the ability to customize that message somehow and submit a pull request I'll add it the project.

**Comment by chevinbrown** [comment]
@jasper502, sorry for the late followup. 

You're welcome to fork/monkey patch this yourself, but I don't think it is in line with the project.
